-- MySQL Script generated by MySQL Workbench
-- Wed Dec 23 20:07:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema filmy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema filmy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `filmy` DEFAULT CHARACTER SET utf8 ;
USE `filmy` ;

-- -----------------------------------------------------
-- Table `filmy`.`filmy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmy`.`filmy` (
  `id` INT NOT NULL,
  `tytuł` VARCHAR(100) NOT NULL,
  `data` INT NOT NULL,
  `certyfikaty` VARCHAR(45) NULL,
  `czas` INT NULL,
  `ocena_filmweb` FLOAT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tytuł_UNIQUE` (`tytuł` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmy`.`rezyserowie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmy`.`rezyserowie` (
  `rezyser_id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rezyser_id`),
  UNIQUE INDEX `imie_UNIQUE` (`imie` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmy`.`gwiazda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmy`.`gwiazda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `imie_UNIQUE` (`imie` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmy`.`gatunek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmy`.`gatunek` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nazwa_UNIQUE` (`nazwa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmy`.`filmy_has_rezyserowie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmy`.`filmy_has_rezyserowie` (
  `filmy_id` INT NOT NULL,
  `rezyserowie_rezyser_id` INT NOT NULL,
  PRIMARY KEY (`filmy_id`, `rezyserowie_rezyser_id`),
  INDEX `fk_filmy_has_rezyserowie_rezyserowie1_idx` (`rezyserowie_rezyser_id` ASC) VISIBLE,
  INDEX `fk_filmy_has_rezyserowie_filmy1_idx` (`filmy_id` ASC) VISIBLE,
  CONSTRAINT `fk_filmy_has_rezyserowie_filmy1`
    FOREIGN KEY (`filmy_id`)
    REFERENCES `filmy`.`filmy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmy_has_rezyserowie_rezyserowie1`
    FOREIGN KEY (`rezyserowie_rezyser_id`)
    REFERENCES `filmy`.`rezyserowie` (`rezyser_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmy`.`filmy_has_gwiazda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmy`.`filmy_has_gwiazda` (
  `filmy_id` INT NOT NULL,
  `gwiazda_id` INT NOT NULL,
  PRIMARY KEY (`filmy_id`, `gwiazda_id`),
  INDEX `fk_filmy_has_gwiazda_gwiazda1_idx` (`gwiazda_id` ASC) VISIBLE,
  INDEX `fk_filmy_has_gwiazda_filmy1_idx` (`filmy_id` ASC) VISIBLE,
  CONSTRAINT `fk_filmy_has_gwiazda_filmy1`
    FOREIGN KEY (`filmy_id`)
    REFERENCES `filmy`.`filmy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmy_has_gwiazda_gwiazda1`
    FOREIGN KEY (`gwiazda_id`)
    REFERENCES `filmy`.`gwiazda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmy`.`gatunek_has_filmy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmy`.`gatunek_has_filmy` (
  `filmy_id` INT NOT NULL,
  `gatunek_id` INT NOT NULL,
  PRIMARY KEY (`filmy_id`, `gatunek_id`),
  INDEX `fk_gatunek_has_filmy_filmy1_idx` (`filmy_id` ASC) VISIBLE,
  INDEX `fk_gatunek_has_filmy_gatunek1_idx` (`gatunek_id` ASC) VISIBLE,
  CONSTRAINT `fk_gatunek_has_filmy_gatunek1`
    FOREIGN KEY (`gatunek_id`)
    REFERENCES `filmy`.`gatunek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gatunek_has_filmy_filmy1`
    FOREIGN KEY (`filmy_id`)
    REFERENCES `filmy`.`filmy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `filmy` ;

-- -----------------------------------------------------
-- Placeholder table for view `filmy`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmy`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `filmy`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `filmy`.`view1`;
USE `filmy`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
